### PR TITLE
Implement all Keystone packages in a Buildroot external tree

### PR DESCRIPTION
**Pull request by grg-haas**
# Keystone BR2 External RFC

This PR proposes a major change to the Keystone build system by moving the main build to entirely within Buildroot. At this time, the individual commits here are fairly complete in the sense that most of them pass individual test runs (i.e. `scripts/run-qemu.sh` followed by `scripts/test-qemu.sh`). However, the CI build is not yet ported over. Therefore, I am opening this PR as more of a request-for-comment rather than a proposed change to merge at this time. 

## Motivation

In the Keystone projects I have been working on, I've generally found it difficult to integrate the Keystone functionality with other codebases. For example, I am working on a project involving the [Polarfire SoC icicle kit ](https://www.microchip.com/en-us/development-tool/MPFS-ICICLE-KIT-ES). While Keystone ostensibly has support for this CPU through the `mpfs` platform in OpenSBI, this functionality is based on some old copied files from Microchip's [HSS](https://github.com/polarfire-soc/hart-software-services). While this approach works, it is fairly ad-hoc and manual. In order to compose Keystone with a more modern HSS, a developer would have to copy the relevant source files over to Keystone, build the SM, and copy the resultant firmware back to the HSS in order to take advantage of their flashing scripts. Similarly, synchronizing packages between different builds is relatively hard. Microchip has their own [BR2 external overlay](https://github.com/linux4microchip/buildroot-external-microchip), and standard development processes such as e.g. merging configuration files, building packages with the right toolchains, etc between this overlay and Keystone is fairly complicated. 

In that sense, it makes sense to separate the Keystone subprojects (`sm`, `sdk`, `driver`, etc) into their own BR2 external overlay. Then, it becomes very easy to combine Keystone with a large variety of other, useful system overlays ranging from vendor board support packages (such as Microchip's) to many other novel features and packages. Separating our subprojects like this would also allow us to more easily bump the versions of components we rely on (such as QEMU or the Linux kernel) by just bumping Buildroot, which takes care of patching and versioning consistency for us. Finally, building everything in Buildroot allows us to take full advantage of its caching mechanism (through `ccache`), which has the potential to accelerate both development and our CI builds.

## Approach

This PR touches quite a lot of files across the Keystone project, so I would recommend looking at the changes by commit instead. Each commit is self-contained, in that applying it creates a fully working/tested Keystone build (verified by running `scripts/run-qemu.sh` followed by `scripts/test-qemu.sh`). The general approach in the patch series is to first instantiate the BR2 external tree in `overlays/keystone`, and then gradually move each component of the build into that tree. Roughly, the order for this is the following:

1. QEMU is ported first, both because it is already included as a package in standard Buildroot and because it is a _host_ package -- that is, it does not need to be cross-compiled. Buildroot includes functionality for patching sources, so the QEMU patching functionality (along with its issues as described in #330 ) is removed from `CMakeLists.txt`.
2. Then, a more controversial change -- rather than relying on a prebuilt toolchain, we port the toolchain to Buildroot instead. At this point, upstream compilers for RISCV are pretty good. I've used self-built newer versions for most of the year where I've been working on Keystone, and have not run into a situation I would describe as a compiler bug. Building the toolchain in Buildroot allows us to start transitioning away from the brittle `fast_setup.sh / source.sh` dependency.
3. Next, we build the bootrom in Buildroot for the QEMU targets which need it. This is a fairly simple port to the Buildroot external system, since it mainly involves just calling `make` in the bootrom's source directory. 
4. Next, we build the Linux kernel and driver in Buildroot. Again, these are fairly simple ports -- Buildroot of course already includes functinoality for building Linux, and also includes a nice infrastructure for building custom kernel modules.
5. We then build the SM in Buildroot. This is a bit more of an involved change. I've noticed when working with the SM that most files under `plat/generic` are just direct copies of the OpenSBI source code, with slight patches to add calls to e.g. `sm_init`, or to build more object files. This is not a very scalable approach since these files would need to be manually updated if we ever decide to bump OpenSBI versions. Instead, we port the SM by using OpenSBI's existing platforming abstraction. This means we can completely eliminate the copied code and instead focus on generically integrating the SM into standard OpenSBI. Note that I've only ported this for the QEMU (`generic`) platform, but expect to do the same for `mpfs` as well.
6. Finally, we port both the SDK and examples into Buildroot.
 
## Benefits

To me, there are a few benefits for structuring Keystone's build system in this way.

- Version bumps for component packages are much easier. With this change, the maintenance burden of updating packages is no longer on Keystone. Instead, we can simply bump the Buildroot tree (which will take care of many patching issues for us) and only focus on maintaining Keystone-specific functionality. To illustrate this, the last commit in the series bumps Buildroot to the latest LTS release (2023.02.2). In doing so, we bump the Linux kernel to a 6.x series, QEMU to 7.2.1, as well as many other toolchain/userspace package changes. As a result, we needed to update the QEMU ROM patch file as well as change some function signatures in the `tests` example (which were arguably bugs anyways).
- Centralized builds like this allow for better buildtime optimizations. I've included a commit in this patch series which enables `ccache` and Buildroot's per-package parallelization option. I've used both of these options for years without any major issues, and they have a quite significant effect on build time. Specifically, I've been able to do full system rebuilds (including toolchain, QEMU, firmware, etc) in about 10 minutes with a warmed up build cache.
  -  I believe this will also have positive downstream effects on other project components, such as the CI and docker image. Rather than relying on the image as a build cache (as discussed in #338 ), we can use an actual compiler cache as the build cache and let the Docker image be used only as a known-tested environment.
 - Composability will be much easier. It will be possible to, for example, pull together the Keystone external tree with the Microchip external tree with other external trees and spin up full systems much more efficiently. This could even be extended to [Yocto](https://www.yoctoproject.org/) layers in the future to maximize this 

## Issues

This approach does also have a few negative points.

- Increased complexity as compared to the standard `CMakeLists.txt`. I believe more people are probably familiar with `cmake` than Buildroot, so forcing users and developers to use another build infrastructure may be a bit of a pain point. Specifically, for example, Buildroot does not track when packages need to be rebuilt. So, a developer making changes the SM would need to first run `make opensbi-dirclean` followed by `make` in order to resynchronize the source code changes. We can mitigate this somewhat by building some infrastructure around source synchronization, i.e. we scan each source file in the SM and if any are newer than the firmware image, we automatically run `make opensbi-dirclean`. I have not implemented this yet.

## Followup

There is some work to be done in order to fully polish this change.

- Fix CI, which has not yet been ported to the new build infrastructure. This may also involve some changes to how we use the Docker image.
- Move all of `overlays/keystone` into its own repository so it can be submoduled by external Buildroot consumers. Currently, the Keystone overlay finds source code by environment variable definition. For each ported package `X`, we  start the build recipe with something like follows:
    ``` 
    ifeq ($(KEYSTONE_<X>),)
	    $(error KEYSTONE_<X> directory not defined)
    endif
    ```
     and then pass the definition `KEYSTONE_<X>=${<X>_srcdir}` in the Buildroot recipe in the main `CMakeLists.txt`. This obviously would not work for BR2 external-only consumers who do not have the wrapping `keystone` repository that actually holds the source code. Therefore, the overlay should support both "in-tree" builds (where the overlay is submoduled in the main `keystone` project and source files can be copied directly) and "out-of-tree" builds where only the external tree is included in some other project (and source code must first be downloaded). This is relatively straightforward to implement (either use `KEYSTONE_<X>_SITE_METHOD=local` or `git`, depending on build type), but I have not done so yet.

## Conclusion

I'd appreciate any feedback on this approach! I strongly believe that this is the right way to go in terms of future build infrastructure for Keystone, but am of course interested in hearing/addressing feedback from others.

### CODE REVIEW

**Comment by dayeol** [comment]
Hey, I ran into this PR and wanted to flag a few things.
- This PR is too huge to be reviewed at once. Is there a way we can split this up? I get that the major part of it is renaming (moving) files, but still it would be great if we had multiple (possibly stacked) PRs.
- Does this mean that Keystone software stack will be tied to the Buildroot? How does it work out when, let's say, someone wants to build/deploy Keystone on a Debian RISC-V machine that they already have?

**Comment by grg-haas** [comment]
> This PR is too huge to be reviewed at once.

I structured the PR such that each commit is a relatively self-contained change which preserves functionality. That is, the tests (`run-qemu.sh` followed by `test-qemu.sh`) should pass after each commit in the series is individually applied. Therefore, reviewing the PR by looking at the per-commit view should be much more feasible. Of course, I can split related commits into their own PRs if need be.

> Does this mean that Keystone software stack will be tied to the Buildroot?

Not necessarily. I see this more like using Buildroot as the top-level build system (as opposed to the current cmake top-level build). Each Keystone component (driver, SDK, examples, etc) still has its own build system which can be called independently (i.e. the driver is a standard Linux kernel module, the SDK has a cmake build, etc). Buildroot is merely used to expose a standardized "build interface" of sorts, which works together neatly with similar overlays from other vendors. For example, I've been able to very easily create a working Keystone build for the Microchip Icicle kit (`mpfs` platform) by pulling their Buildroot overlay, combining it with this one, and adding a few small patches as needed. In contrast, in the cmake build system, I would have had to change the Linux kernel submodule version, manually add more patch files to the SM (using the cmake macros), etc etc. In my experience, structuring top-level build systems like this is really good for making integration easier.

**Comment by dayeol** [comment]
I have a quick question,
I realized that many of the changes are rename of the directories (e.g., `sm` --> `firmware/sm`)
Were these renaming/reorg of directory necessary for the proposed change?

**Comment by grg-haas** [comment]
It is not necessary no, but I do think that it makes the root source tree look a bit better. I've also added a few new packages under `software` as part of my research, and it visually looks "nicer" to keep these in a subfolder rather than the toplevel

**Comment by dayeol** [comment]
I understand that the renaming / restructuring has benefits, but I am worried that this might create too much conflict burden to many un-merged branches. Would you be able to get rid of renamings that are not necessary? We might be able to start with creating a symlink to make it compatible with your project.

**Comment by grg-haas** [comment]
I can definitely push a branch excluding the renames, sure -- I'll put that in tomorrow. I will note that rebasing my own feature branches (some of which were developed before this PR) went pretty well. Git was smart of enough to keep track of the file renames, and only complained when I had created a new file in a directory which no longer existed (i.e. created a file under `runtime/`, which now needed to be in `software/runtime/`) -- however, even in this case it suggested moving the file to the correct location. I just needed to do `git add software/runtime/...` and a `git rebase --continue` to fixup

**Review by dayeol — APPROVED** [review]
Thank you very much for pushing this huge effort!
This will be very helpful to simplify adding Keystone support on different platforms.
Also, bumping external modules (e.g., toolchain, linux, etc) would be much simpler.

I approve the PR.

As a follow-up, please modify the documents and CI accordingly in separate PRs :)
Also, please communicate with the community (forum) that this change has been merged.

**Pull request merged**
