### PR TITLE
Writes the remote attestation tutorial.

### PR DESCRIPTION
**Pull request by zchn**
This is dependent on the pull request on keystone-sdk: https://github.com/keystone-enclave/keystone-sdk/pull/77. DO NOT merge before merging https://github.com/keystone-enclave/keystone-sdk/pull/77.

Also adds the attestation example to the continous integration tests to prevent regression.

### CODE REVIEW

**Comment by zchn** [comment]
Hrmmm, somehow the PR fails to build on circleci, will close this one and open a new one once I figure out why and fix the problem...

**Comment by zchn** [comment]
I've been having trouble pin-pointing the problem encountered in the CI tests. Here is one example log: https://app.circleci.com/pipelines/github/zchn/keystone/30/workflows/1350eef4-9fa1-4f97-b401-f7eac1d461ca/jobs/105 (see also the log file at [0.txt](https://github.com/keystone-enclave/keystone/files/7048319/0.txt)).

From the log file I don't see a clear error message, and I was not able to repro it on my local machine (it runs successfully on my machine). Any advice on how to figure investigate it? Thanks!

**Comment by zchn** [comment]
Found the problem: 

```
make[2]: *** No rule to make target 'sm.build/platform/generic/firmware/fw_payload.bin', needed by 'examples/attestation/pkg/fw_payload.bin'.  Stop.
make[2]: Leaving directory '/keystone/build64' 
CMakeFiles/Makefile2:1258: recipe for target 'examples/attestation/CMakeFiles/attestor-package.dir/all' failed
make[1]: *** [examples/attestation/CMakeFiles/attestor-package.dir/all] Error 2
make[1]: Leaving directory '/keystone/build64' 
Makefile:86: recipe for target 'all' failed 
make: *** [all] Error 2
```

Now trying to figure out a fix....

**Comment by zchn** [comment]
Attempted a fix but didn't work: https://github.com/zchn/keystone-sdk/commit/f449d1cfbf43499813c38f8f83931d797982eed6

Will keep trying other options.

**Comment by zchn** [comment]
#183 is related to this.

**Comment by zchn** [comment]
All tests are passing now after applying the workaround we discussed (#251 ) :)

**Review by dayeol — APPROVED** [review]
LGTM!

**Pull request merged**
