### PR TITLE
Qemu virtio-rng device

### PR DESCRIPTION
**Pull request by kazkojima**
Hi,

There are warnings for random device in dmesg when runing on qemu.
```
[    0.741849] random: dd: uninitialized urandom read (512 bytes read)
[    1.119964] random: dropbear: uninitialized urandom read (32 bytes read)
```
Also getrandom() call blocks in the tiny test:
```
#include <sys/random.h>

int main() { char buf[8]; return getrandom(buf, 8, 0); }
```
With adding "-device virtio-rng-pci" to the qemu command line, the above test doesn't block and there are no warnings for random from kernel.

### CODE REVIEW

**Comment by dkohlbre** [comment]
Hi, can you rebase this off `dev` rather than `master`? It'll keep the commit history cleaner.
Thanks!

(And yeah, this looks like more problems related to the hackery to get current linux running on bbl.)

**Comment by kazkojima** [comment]
Ugh! I've missed to checkout dev. Sorry for that.
Should I open new PR with withdrawing this PR?

**Comment by dkohlbre** [comment]
if you force-push to your branch with the rebase it works fine. If another PR is easier for you its just as easy from our end!

**Comment by kazkojima** [comment]
Thanks! I've sent a new PR. Hope it's ok this time.

**Comment by dkohlbre** [comment]
Closed in favor of: https://github.com/keystone-enclave/keystone/pull/160

**Pull request closed without merging**
