### PR TITLE
Add CVA6 Keystone support

### PR DESCRIPTION
**Pull request by andreaskuster**
This PR adds all puzzle pieces to build and create the Keystone image (sm/driver/linux/..) and has been tested (hello-world & tests) on the lastest [CVA6](https://github.com/openhwgroup/cva6) RISC-V core from ETH Zurich using the FPGA/Genesys 2 flow. Furthermore, the instructions have been adjusted to incoperate relevant information.

Please let me know if this PR is good to go, or if adjustments are required from my side.

### CODE REVIEW

**Comment by dayeol** [comment]
please let me know if this is ready to be reviewed!

**Comment by andreaskuster** [comment]
> 
> 
> please let me know if this is ready to be reviewed!


I just changed it to be ready for review. The reason I kept it in `WIP` is the [issue #259](https://github.com/keystone-enclave/keystone/issues/259), with the `Attestation report is invalid`, but we can also discuss/resolve this during review.

```
# insmod keystone-driver.ko
[   69.725113] keystone_driver: loading out-of-tree module taints kernel.
[   69.928969] keystone_enclave: keystone enclave v1.0.0
# ./tests.ke
Verifying archive integrity... All good.
Uncompressing Keystone Enclave Package
testing stack
testing loop
testing malloc
testing long-nop
testing fibonacci
testing fib-bench
testing attestation
Attestation report is invalid
testing untrusted
Enclave said: hello world!
Enclave said: 2nd hello world!
Enclave said value: 13
Enclave said value: 20
testing data-sealing
Enclave said: Sealing key derivation successful!
```

**Comment by dayeol** [comment]
Everything looks good to me, but we need to make sure the document is more structured so that we can easily add additional platforms in the future. Could you separate the CVA6 and HiFive documents (put them on different pages) and list the supported platforms in the original HW deployment document?

**Comment by andreaskuster** [comment]
@dayeol 
I separated the deployment guides in two separate pages (CVA6 and Unleashed), while keeping the original hardware depolyment guide as an index. It is therefore ready for review again.

**Comment by dayeol** [comment]
Awesome! looks good to me

**Comment by asyarifstudio** [comment]
hi @andreaskuster.

I'm starting to integrate Keystone to CVA6 and it's really awesome that you've done it. However when I follow the steps in https://github.com/keystone-enclave/keystone/blob/master/CVA6_INSTALL.md, it seems the linux is not booted, and I can only see this in my SSH connection 

`copying boot image .............................................. done!`

I notice also, compared to the guide in the https://github.com/openhwgroup/cva6-sdk, the flashing to the SDK in your doc is kind of missing the Linux part in the second partition of the SD. 

is there any step that you think I missed? to note, I can launch the QEMU with the keystone enclave.

Thanks a lot for your help.

**Comment by andreaskuster** [comment]
> hi @andreaskuster.
> 
> I'm starting to integrate Keystone to CVA6 and it's really awesome that you've done it. However when I follow the steps in https://github.com/keystone-enclave/keystone/blob/master/CVA6_INSTALL.md, it seems the linux is not booted, and I can only see this in my SSH connection
> 
> `copying boot image .............................................. done!`
> 
> I notice also, compared to the guide in the https://github.com/openhwgroup/cva6-sdk, the flashing to the SDK in your doc is kind of missing the Linux part in the second partition of the SD.
> 
> is there any step that you think I missed? to note, I can launch the QEMU with the keystone enclave.
> 
> Thanks a lot for your help.

Hi @asyarifstudio 

Thank you for reaching out, and I am glad you like it. Were you able to resolve the issue in the meantime? If not, maybe it would be cleaner to open a separate issue, as it would be better trackable.

Nevertheless, I can give you a few pointers to look at.

1) Looking at the setup, I saw that the forked repo is still linked there (i.e. https://github.com/andreaskuster/keystone.git). Have you used that one for building Keystone, or did you use this repo instead? Maybe try mine, as some recent changes might influence the outcome.

2) Make sure that you start clean (i.e. delete and re-create the build directory), and make sure that CMake catches the -Dcva6=y flag (check in the logs). 

3) Make sure no errors are popping up on the command

And last but not least, a note about the output you see: It is expected that no output logs can be seen until the bootup process ends in the Linux environment since there is no hardware/driver in place to display early boot logs. For that, you should either use simulation or add corresponding hardware/driver support.

Unfortunately, I do not have a `Genesys 2` FPGA board at hand, but feel free to let me know if you weren't able to resolve it, and I will check with some colleagues if they can help.

**Pull request merged**
