### PR TITLE
Initial instruction of Keystone on FPGA vc707

### PR DESCRIPTION
**Pull request by mcd500**
I am finally uploaded the documentation of how to build and run keystone on FPGA vc707.
I really appreciate for any kind of comment.

### CODE REVIEW

**Comment by dkohlbre** [comment]
This looks good to me!
I don't have a VC707 to test on right now, so we may need to tag you if any issues come up.

@dayeol any objections to merging these instructions?

**Comment by mcd500** [comment]
Sure, no problem for pointing me for questions related on VC707, thanks.

**Comment by mcd500** [comment]
By the way, this markdown doc is not linked from the README.md. Do you mind adding the link from where is appropriate?

**Comment by mcd500** [comment]
@dayeol Gentle ping? :)

**Comment by dayeol** [comment]
Sorry for the delay!
Merged! Ideally we will include the instruction in the official doc before we release.

**Comment by mcd500** [comment]
Thanks for merging it!

**Pull request merged**
