### PR TITLE
Allow out-of-tree builds for tests, clean up CMakeLists

### PR DESCRIPTION
**Pull request by archshift**
Just a few build system improvements.

WRT the CMake stuff, `set(... CACHE)` is better practice for variables designed to be modified by the user. If you use a tool like `ccmake` (a very useful cmake TUI!) these are the variables that show up.

I also made the tests/tests directory run out of tree builds, to make it easy to wipe away build artifacts. I also changed the Makefile lazy assignments (using `foo = bar`) to use eager ones (`foo := bar`). This is much faster because the right hand side is only expanded once, at assignment time.

### CODE REVIEW

**Comment by dkohlbre** [comment]
This lgtm, builds fine on my end.
@dayeol since you wrote the CMake setup, can you take a quick look?

**Comment by dayeol** [comment]
LGTM. One thing that I'm not sure is if this will still work with the tutorials (http://docs.keystone-enclave.org/en/latest/Getting-Started/Tutorials/index.html).
I think vault.sh for those tutorials should be also updated.
Can you confirm? @archshift

**Comment by archshift** [comment]
@dayeol I didn't change anything about how the SDK is built or where its artifacts are stored, so any user-written vault scripts should still work the same way. I should go through the docs and rename the CMake defines where appropriate though.

**Comment by dayeol** [comment]
Okay, let's merge after we have the docs then

**Comment by archshift** [comment]
@dayeol should be good to go

**Comment by archshift** [comment]
Made it so we don't rerun the Linux makefile every time. Incremental builds are much faster now :)

**Pull request merged**
