### PR TITLE
Build new cmake-based Eyrie

### PR DESCRIPTION
**Pull request by grg-haas**
This PR slightly changes the `add_eyrie_runtime` macro in order to accommodate the new Cmake-based runtime build (https://github.com/keystone-enclave/keystone-runtime/pull/63)

### CODE REVIEW

**Comment by dayeol** [comment]
Is this ready for review?

**Comment by grg-haas** [comment]
Hi Dayeol, yes it is! Sorry, for some reason it seems I can't request reviews

**Comment by dayeol** [comment]
I fixed RV64 tests and temporarily disabled failing tests. Thus, this should pass the tests before get merged in

**Comment by dayeol** [comment]
Do you know why the tests were not triggered?

**Comment by grg-haas** [comment]
I'm not sure -- do these usually run for PRs?

It might be important to merge the changes for the runtime first and tag a new release, since the `add_eyrie_runtime` macro clones a specific tag as part of the build process (currently `v1.0.0` for most examples I believe). However, there are incompatible build changes since `build.sh` no longer exists. This would probably make the tests fail.

**Comment by dayeol** [comment]
Could you check if this is the case? (ref: https://support.circleci.com/hc/en-us/articles/360008097173-Troubleshooting-why-pull-requests-are-not-triggering-jobs-on-my-organization-)
> A user who submits a pull request to your repository from a fork, but no pipeline is triggered with the pull request. This can happen when the user is following the project fork on their personal account rather than the project itself on CircleCI.

**Pull request closed without merging**
